export const CONFIG = {
    API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
    WHATSAPP_NUMBER: process.env.REACT_APP_WHATSAPP_NUMBER,
    GST_PERCENTAGE: Number(process.env.REACT_APP_GST_PERCENTAGE) || 18,
    ADVANCE_PERCENTAGE: Number(process.env.REACT_APP_ADVANCE_PERCENTAGE) || 50,
    CURRENCY_SYMBOL: process.env.REACT_APP_CURRENCY_SYMBOL || '₹',
    CURRENT_TIMESTAMP: "2025-03-07 06:34:54",
    CURRENT_USER: "Sree"
  };